# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateTimeField(blank=True, null=True)),
                ('deviceId', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('loc', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('AQI', models.FloatField(blank=True, null=True)),
                ('PM10', models.FloatField(blank=True, null=True)),
                ('PM25', models.FloatField(blank=True, null=True)),
                ('CO', models.FloatField(blank=True, null=True)),
                ('O3', models.FloatField(blank=True, null=True)),
                ('SO2', models.FloatField(blank=True, null=True)),
                ('NO2', models.FloatField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('hum', models.FloatField(blank=True, null=True)),
                ('WD', models.FloatField(blank=True, null=True)),
                ('WS', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('rainGaige', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['t'],
            },
        ),
    ]
